### ISSUE TITLE
Silent failure when running a workflow by copying and pasting workflow ID

### ISSUE THREAD

**Issue by isaacliao** [StanfordBioinformatics/loom#187] opened 2016-08-30 19:12 UTC
Reported by Sowmi. Trying to run a workflow by copying and pasting the workflow ID fails silently.
The server returns a run request ID, but doesn’t actually run it. However, manually typing in the workflow ID works.

**Comment by nhammond** [comment] 2016-08-30 19:15
Not clear. Is this using the "loom run" command in both cases?

**Comment by isaacliao** [comment] 2016-08-30 19:57
CC'ing Sowmi for more details.

________________________________

**Comment by nhammond** [comment] 2016-10-13 00:21
Closing as unable to reproduce.

**Closed by nhammond** 2016-10-13 00:21 UTC
Labels: not reproducible
