### ISSUE TITLE
UTC AttributeError in server's async log

### ISSUE THREAD

**Issue by isaacliao** [StanfordBioinformatics/loom#351] opened 2017-04-21 21:13 UTC
```
PLAY [Stop and/or cleanup the Loom task runner localhost] **********************

TASK [Gathering Facts] *********************************************************
[2017-04-21 21:08:00,164: INFO/MainProcess] Received task: api.async._run_task[b13da602-7451-42fc-b66e-6c736faac496]
[2017-04-21 21:08:00,179: INFO/MainProcess] Task api.async._finish_task_attempt[22a1394b-52dc-482d-bade-5279a30c79be] succeeded in 0.180449713996s: None
[2017-04-21 21:08:00,235: INFO/MainProcess] Received task: api.async._cleanup_task_attempt[691c2021-b34a-45d8-bc64-6af339872156]
[2017-04-21 21:08:00,273: INFO/MainProcess] Task api.async._cleanup_task_attempt[691c2021-b34a-45d8-bc64-6af339872156] succeeded in 0.0177123940084s: None
[2017-04-21 21:08:00,275: ERROR/MainProcess] Task api.async._run_task[b13da602-7451-42fc-b66e-6c736faac496] raised unexpected: AttributeError("'module' object has no attribute 'UTC'",)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 367, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/celery/app/trace.py", line 622, in __protected_call__
    return self.run(*args, **kwargs)
  File "/loomengine/loomengine/master/api/async.py", line 110, in _run_task
    args=[task_attempt])
  File "/loomengine/loomengine/master/api/async.py", line 129, in _run_with_heartbeats
    tzinfo=timezone.UTC())
AttributeError: 'module' object has no attribute 'UTC'
```
However, tasks run successfully.

**Comment by nhammond** [comment] 2017-04-21 21:20
Caused by django version upgrade. Formerly django.utils.timezone.UTC(), now django.utils.timezone.utc. Fixed in 6ba641cd0a6df02ca7401128a394ae6d5c37182c

**Closed by nhammond** 2017-04-21 21:20 UTC
