### ISSUE TITLE
ImportError: No module named functools32

### ISSUE THREAD

**Issue by pbilling** [StanfordBioinformatics/loom#461] opened 2017-09-28 20:57 UTC
```
$ loom test unit
Traceback (most recent call last):
<...>
  File "/Users/pbilling/Documents/GitHub/loom/loom_libs/lib/python2.7/site-packages/jsonschema/compat.py", line 35, in <module>
    from functools32 import lru_cache
ImportError: No module named functools32
$ pip install --upgrade functools32
Requirement already up-to-date: functools32 in /Library/Python/2.7/site-packages
$ pip freeze
<...>
backports.functools-lru-cache==1.2.1
functools32==3.2.3.post2
```

**Comment by nhammond** [comment] 2017-09-28 21:16
Issue caused by DNAnexus SDK installer modifying PYTHONPATH in .bashrc. Fixed by un-setting their changes.

**Closed by nhammond** 2017-09-28 21:16 UTC
